"""Initial migration

Revision ID: 90e6a4598441
Revises: 
Create Date: 2026-02-05 10:59:07.287927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e6a4598441'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_points',
    sa.Column('access_pt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ap_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('access_pt_id')
    )
    op.create_index(op.f('ix_access_points_ap_type'), 'access_points', ['ap_type'], unique=False)
    op.create_table('customers',
    sa.Column('customer_guid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_integration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('customer_guid')
    )
    op.create_index(op.f('ix_customers_customer_guid'), 'customers', ['customer_guid'], unique=False)
    op.create_table('workflows',
    sa.Column('workflow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_index(op.f('ix_workflows_workflow_type'), 'workflows', ['workflow_type'], unique=True)
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('customer_guid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['customer_guid'], ['customers.customer_guid'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_index(op.f('ix_workspaces_workspace_id'), 'workspaces', ['workspace_id'], unique=False)
    op.create_table('auths',
    sa.Column('auth_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('json_data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('integrations',
    sa.Column('integration_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('source_access_pt_id', sa.Integer(), nullable=False),
    sa.Column('dest_access_pt_id', sa.Integer(), nullable=False),
    sa.Column('integration_type', sa.String(length=100), nullable=False),
    sa.Column('usr_sch_cron', sa.String(length=100), nullable=True),
    sa.Column('usr_sch_status', sa.String(length=20), nullable=True),
    sa.Column('usr_timezone', sa.String(length=50), nullable=True),
    sa.Column('utc_next_run', sa.DateTime(), nullable=True),
    sa.Column('utc_sch_cron', sa.String(length=100), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=True),
    sa.Column('json_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auth_id'], ['auths.auth_id'], ),
    sa.ForeignKeyConstraint(['dest_access_pt_id'], ['access_points.access_pt_id'], ),
    sa.ForeignKeyConstraint(['source_access_pt_id'], ['access_points.access_pt_id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('integration_id')
    )
    op.create_index(op.f('ix_integrations_integration_type'), 'integrations', ['integration_type'], unique=False)
    op.create_index(op.f('ix_integrations_workspace_id'), 'integrations', ['workspace_id'], unique=False)
    op.create_table('integration_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('dag_run_id', sa.String(length=255), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('ended', sa.DateTime(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('execution_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.integration_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_integration_runs_dag_run_id'), 'integration_runs', ['dag_run_id'], unique=False)
    op.create_index(op.f('ix_integration_runs_integration_id'), 'integration_runs', ['integration_id'], unique=False)
    op.create_table('integration_run_errors',
    sa.Column('error_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['integration_runs.run_id'], ),
    sa.PrimaryKeyConstraint('error_id')
    )
    op.create_index(op.f('ix_integration_run_errors_run_id'), 'integration_run_errors', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_run_errors_run_id'), table_name='integration_run_errors')
    op.drop_table('integration_run_errors')
    op.drop_index(op.f('ix_integration_runs_integration_id'), table_name='integration_runs')
    op.drop_index(op.f('ix_integration_runs_dag_run_id'), table_name='integration_runs')
    op.drop_table('integration_runs')
    op.drop_index(op.f('ix_integrations_workspace_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_integration_type'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_table('auths')
    op.drop_index(op.f('ix_workspaces_workspace_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_workflows_workflow_type'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_customers_customer_guid'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_access_points_ap_type'), table_name='access_points')
    op.drop_table('access_points')
    # ### end Alembic commands ###
