"""Add dead_letter_messages table

Revision ID: b3f1a2c7d890
Revises: 90e6a4598441
Create Date: 2026-03-15 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f1a2c7d890'
down_revision: Union[str, None] = '90e6a4598441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_messages',
    sa.Column('dlq_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('source_topic', sa.String(length=255), nullable=False),
    sa.Column('consumer_group', sa.String(length=255), nullable=False),
    sa.Column('message_key', sa.String(length=255), nullable=True),
    sa.Column('original_message', sa.Text(), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('dlq_id')
    )
    op.create_index(op.f('ix_dead_letter_messages_integration_id'), 'dead_letter_messages', ['integration_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_messages_message_key'), 'dead_letter_messages', ['message_key'], unique=False)
    op.create_index(op.f('ix_dead_letter_messages_status'), 'dead_letter_messages', ['status'], unique=False)
    op.create_index('ix_dlq_status_created', 'dead_letter_messages', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dlq_status_created', table_name='dead_letter_messages')
    op.drop_index(op.f('ix_dead_letter_messages_status'), table_name='dead_letter_messages')
    op.drop_index(op.f('ix_dead_letter_messages_message_key'), table_name='dead_letter_messages')
    op.drop_index(op.f('ix_dead_letter_messages_integration_id'), table_name='dead_letter_messages')
    op.drop_table('dead_letter_messages')
    # ### end Alembic commands ###
